# Generated by Django 5.2 on 2025-04-15 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_remove_partner_business_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('pickup_time', models.DateTimeField()),
                ('drop_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_transit', 'In Transit'), ('arriving', 'Arriving'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.customer')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.partner')),
                ('partner_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.partnerverification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
