# Generated by Django 5.2 on 2025-05-22 20:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_description_booking_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drop_latlng',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_latlng',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
