# Generated by Django 5.2.1 on 2025-06-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_drop_latlng_booking_pickup_latlng'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drop_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
