# Generated by Django 5.2.1 on 2025-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_drop_otp_booking_pickup_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='boxes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='helper_required',
            field=models.BooleanField(default=False),
        ),
    ]
