# Generated by Django 5.2.1 on 2025-07-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_actual_duration_minutes_and_more'),
        ('vehicles', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vehicles.vehicletype'),
        ),
    ]
