# Generated by Django 5.2.1 on 2025-11-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('mini_truck', 'Mini Truck'), ('truck', 'Truck')], max_length=20, unique=True)),
                ('base_fare', models.DecimalField(decimal_places=2, help_text='Base fare for this vehicle', max_digits=6)),
                ('fare_per_km', models.DecimalField(decimal_places=2, help_text='Fare per km', max_digits=6)),
                ('capacity_in_kg', models.PositiveIntegerField(help_text='Maximum load capacity in KG')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
            },
        ),
    ]
