"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file for local development
try:
    from dotenv import load_dotenv
    BASE_DIR = Path(__file__).resolve().parent.parent
    env_default_path = os.path.join(BASE_DIR, '..', '.env')
    if os.path.exists(env_default_path):
        load_dotenv(dotenv_path=env_default_path)
    else:
        load_dotenv()  # fallback to default behavior
except ImportError:
    # python-dotenv not installed, continue without it
    pass

# Check if we're in local development mode
LOCAL_DEV = os.getenv('LOCAL_DEV', 'False').lower() == 'true'

# For local development, use local_settings overrides
if LOCAL_DEV:
    try:
        from .local_settings import get_secure_env_var
        print("Using local development settings")
    except ImportError:
        pass

# GDAL library path - set only if not in Docker (where it's in system path)
if not os.path.exists('/.dockerenv') and os.path.exists('/opt/homebrew/Cellar/gdal'):
    os.environ['GDAL_LIBRARY_PATH'] = '/opt/homebrew/Cellar/gdal/3.11.0/lib/libgdal.dylib'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

def get_secure_env_var(var_name, default=None):
    """
    Get environment variable.
    
    In production (ECS), secrets are automatically decrypted by ECS from SSM Parameter Store
    and injected as plain environment variables. No additional decryption is needed.
    
    Args:
        var_name (str): Environment variable name
        default: Default value if not found
        
    Returns:
        str: Environment variable value or default
    """
    if LOCAL_DEV:
        # For local development, check if local_settings provides override
        try:
            from .local_settings import get_secure_env_var as local_get_var
            return local_get_var(var_name, default)
        except (ImportError, AttributeError):
            pass
    
    # Default: read from environment (works for both local .env and ECS SSM secrets)
    return os.getenv(var_name, default)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secure_env_var('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY environment variable is not set. "
        "Please set SECRET_KEY in your ECS task definition or environment variables. "
        "For AWS ECS, you can use AWS Systems Manager Parameter Store or Secrets Manager."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG_VALUE = get_secure_env_var('DEBUG', 'False')
DEBUG = DEBUG_VALUE.lower() == 'true' if DEBUG_VALUE else False

APPEND_SLASH = False

ALLOWED_HOSTS = (get_secure_env_var('ALLOWED_HOSTS') or '*').split(',')


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',  # or 'json' if using log processing
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'driver-loc-cache',
    }
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_gis',
    'corsheaders',
    'graphene_django',
    'users',
    'vehicles',
    'bookings',
    'wallet',
    'marketplace',
    'storages',
    'channels'
]

GRAPHENE = {
    "SCHEMA": "main.schema.schema",  # Path to your schema
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Support DATABASE_URL format (from SSM Parameter Store in ECS)
DATABASE_URL = get_secure_env_var('DATABASE_URL')
if DATABASE_URL:
    # Parse DATABASE_URL: postgres://user:password@host:port/dbname
    import urllib.parse
    parsed = urllib.parse.urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': parsed.path[1:],  # Remove leading '/'
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': parsed.hostname,
            'PORT': parsed.port or '5432',
        }
    }
else:
    # Fallback to individual environment variables
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': get_secure_env_var('DB_NAME', 'postgres'),
            'USER': get_secure_env_var('DB_USER', 'vikash'),
            'PASSWORD': get_secure_env_var('DB_PASSWORD'),
            'HOST': get_secure_env_var('DB_HOST', 'last-minute-dev.cm96escgy66l.us-east-1.rds.amazonaws.com'),
            'PORT': get_secure_env_var('DB_PORT', '5432'),
        }
    }

# AUTH_USER_MODEL = 'users.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ASGI_APPLICATION = 'main.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

AWS_MEDIA_BUCKET_NAME = get_secure_env_var('AWS_MEDIA_BUCKET_NAME', 'lastminute-us-east-1-media')
AWS_MEDIA_CUSTOM_DOMAIN = get_secure_env_var('AWS_MEDIA_CUSTOM_DOMAIN')
DEFAULT_FILE_STORAGE = 'main.storage_backends.MediaStorage'
AWS_MEDIA_DOMAIN = AWS_MEDIA_CUSTOM_DOMAIN or f'{AWS_MEDIA_BUCKET_NAME}.s3.amazonaws.com'
MEDIA_URL = f'https://{AWS_MEDIA_DOMAIN}/'

AWS_ACCESS_KEY_ID = get_secure_env_var('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = get_secure_env_var('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = get_secure_env_var('AWS_STORAGE_BUCKET_NAME', 'zappa-deployments-last-minute')
AWS_S3_REGION_NAME = get_secure_env_var('AWS_S3_REGION_NAME', 'us-east-1')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = True
AWS_SNS_ARN = get_secure_env_var('AWS_SNS_ARN', 'arn:aws:sns:us-east-1:957118235304:app/GCM/last-minute')

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'  # Always set for non-S3 case
static_dir = os.path.join(BASE_DIR, 'static')
if os.path.exists(static_dir):
    STATICFILES_DIRS = [static_dir]