# Generated by Django 5.2 on 2025-04-13 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_full_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_license', models.CharField(blank=True, max_length=50)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='documents/licenses/')),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='documents/registration/')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='documents/selfies/')),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='users.partner')),
            ],
        ),
    ]
