# Generated by Django 5.2.1 on 2025-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_partner_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
