# Generated by Django 5.2.1 on 2025-06-19 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_partner_is_live'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to='wallet.partnerwallet'),
        ),
    ]
