# Generated by Django 5.2 on 2025-04-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_partnerverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerverification',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('mini_truck', 'Mini Truck'), ('truck', 'Truck')], default=None, max_length=50),
        ),
    ]
