# Generated by Django 5.2 on 2025-04-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_partnerverification_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='partnerverification',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerverification',
            name='owner_full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partnerverification',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerverification',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
