# Generated by Django 5.2.1 on 2025-07-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seller'),
        ('vehicles', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='vehicles.vehicletype'),
        ),
    ]
